name: Cargo Build & Test

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          # Universal macOS binary is supported as universal-apple-darwin.
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --bin infuse_decoder --verbose
      - run: cargo build --bin infuse_decoder_cli --verbose
